### ISSUE TITLE
Transformation error

### ISSUE THREAD

**Issue by shannonmoeller** [douglasduteil/study-node-path-es6#1]
Any idea what's causing this?

https://travis-ci.org/douglasduteil/study-node-path-es6/jobs/57027484#L144-L150

I get the same error when running this locally in my project.

```sh
babel-node ./node_modules/.bin/isparta cover --report text --report lcov ./node_modules/.bin/_mocha
```

**Comment by douglasduteil** [comment]
wow dunno... I will investigate. Thanks

**Comment by shannonmoeller** [comment]
Anything?

**Comment by tysoncadenhead** [comment]
I'm seeing that issue too on my project. For some reason, the `_mocha` script has a return inside an if statement. I'm not sure if Mocha intends for that script to be wrapped or something, but the issue is definitely with a return happening directly inside the global context.

**Comment by shannonmoeller** [comment]
The `return` is totally valid in a Node context. It's just weird that _mocha is being treated as ES6. Stuff in node_modules usually isn't parsed by babel-node, but in this case we're reaching into node_modules directly so it doesn't know to skip it.

**Comment by thegoleffect** [comment]
https://github.com/douglasduteil/isparta/issues/47 clone latest mocha to solve the problem (or just wait for them to publish 2.3.0)

**Comment by douglasduteil** [comment]
Hi @shannonmoeller @tysoncadenhead  @thegoleffect  

After some code surfing :surfer: 
I found out that the problem comes form the `istanbul` default exclusion pattern that don't match for `node_modules/.bin/_mocha`

Here is deduction http://tonicdev.com/douglasduteil/isparta-68-transformation-error-return-original-code
